[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
owo-colors = "3.5.0"
rayon = "1.8.0"
regex = "1.10.2"
stopwatch = "0.0.7"

[dev-dependencies]
test-case = "2.2.2"
