[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
maplit = "1.0.2"
owo-colors = "3.5.0"
phf = { version = "0.11.1", features = ["macros"] }
regex = "1.10.2"
stopwatch = "0.0.7"

[dev-dependencies]
test-case = "2.2.2"
